[project]
name = "vm-creation"
version = "0.1.0"
description = "Create an openstack VM"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible>=11.7.0",
    "python-openstackclient>=7.4.0",
]
